# mkdocs.yml
site_name: ".agent Community"
site_url: https://docs.agentcommunity.org

# Repository
repo_url: https://github.com/agentcommunity/docs

# Theme Configuration
theme:
  name: material
  favicon: https://www.agentcommunity.org/favicon.ico
  logo: assets/logo.svg

  font:
    text: Inter
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  palette:
    # DARK MODE CONFIGURATION (Stays the same)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      logo: assets/logo-white.svg
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # LIGHT MODE CONFIGURATION (Now with a dark header)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      logo: assets/logo-white.svg   # <-- Use the WHITE logo here too
      primary: black               # <-- THE KEY CHANGE: Set primary to black
      accent: blue                 # <-- Links in the light content will be blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - navigation.sections

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agentcommunity


# Custom CSS for wider layout
extra_css:
  - stylesheets/custom.css

# Extra JavaScript for Mermaid support
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js


# Main Site Navigation
nav:
  - 'Home': 'index.md'
  - 'Work Items':
      - 'Overview': 'specs/index.md'
      - 'Agent Interface Discovery':
          - 'Introduction (aid)': 'specs/aid/introduction.md'
          - 'Design Rationale (aid)': 'specs/aid/rationale.md'
          - 'Specification (aid)': 'specs/aid/spec-v1.md'

  - 'Discussions': 'https://github.com/orgs/agentcommunity/discussions'

# Markdown Extensions
markdown_extensions:
  - attr_list # Lets us add classes to icons, like { .lg .middle }
  - md_in_html # The most important one: allows grids to work at all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details



plugins:
  - search
  - social:
      cards_layout: custom
      cards_layout_options:
        font_family: Inter