# mkdocs.yml
site_name: ".agent Community"
site_url: https://docs.agentcommunity.org
use_directory_urls: true

# Repository
repo_url: https://github.com/agentcommunity/docs
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  favicon: https://www.agentcommunity.org/favicon.ico
  logo: assets/logo.svg

  font:
    text: Inter
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    view: fontawesome/brands/markdown
    tag:
      new: material/new-box  # Icon for NEW tag

  palette:
    # DARK MODE CONFIGURATION (Stays the same)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      logo: assets/logo-white.svg
      primary: black
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # LIGHT MODE CONFIGURATION (Now with a dark header)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      logo: assets/logo-white.svg   # <-- Use the WHITE logo here too
      primary: black               # <-- THE KEY CHANGE: Set primary to black
      accent: blue                 # <-- Links in the light content will be blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - content.action.view
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.expand
    - toc.follow
    - content.code.copy
    - content.code.annotate

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agentcommunity


# Custom CSS for wider layout
extra_css:
  - stylesheets/custom.css

# Extra JavaScript for Mermaid support
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js


# Main Site Navigation
nav:
  - Home: index.md
  - Work Items: work-items/index.md
  - Agent Interface Discovery (AID):
    - Introduction: aid/index.md
    - Design Rationale: 'aid/rationale.md'
    - v1:
      - Specification: aid/v1/specification.md
      - JSON Schema: aid/v1/aid.schema.json
    - Tools (Generator / Resolver / Validator): aid/generator.md
    - Versioning: aid/versioning.md
  - 'Discussions': 'https://github.com/orgs/agentcommunity/discussions'

# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details

plugins:
  - search
  - meta
  - tags
  - social: # <--- CORRECT LOCATION
      cards: true
  - redirects:
      redirect_maps:
        'specs/aid/introduction.md': 'aid/index.md'
        'specs/aid/rationale.md': 'aid/rationale.md'
        'specs/aid/spec-v1.md': 'aid/v1/specification.md'
        'specs/aid/aid.schema.json': 'aid/v1/aid.schema.json'

# Tags Configuration
extra:
  tags:
    NEW: new
    v1: version
    '2025-06-19': date

# Custom CSS for tag styling
extra_css:
  - stylesheets/custom.css