name: Deploy Docs

on:
  push:
    paths:
      - docs/**          # real content
      - mkdocs.yml
      - requirements.txt
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build MkDocs
        run: |
          pip install -r requirements.txt
          mkdocs build                     # → ./site

      - name: Install Vercel CLI
        uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install -g vercel@latest  # puts `vercel` on $PATH

      - name: Deploy to Vercel (prod)
      env:
          VERCEL_ORG_ID:      ${{ secrets.VERCEL_ORG_ID }}       # add this secret
          VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID }}   # add this secret
      run: |
          vercel deploy site --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
    