name: Deploy Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - requirements.txt
      - vercel.json
      - .vercel/project.json
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Docs
        run: |
          pip install -r requirements.txt
          mkdocs build

      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }} site
