name: Deploy Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - requirements.txt
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Docs
        run: mkdocs build

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy to Vercel
        run: vercel deploy --prod --yes --token ${{ secrets.VERCEL_TOKEN }} site
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


