name: Deploy Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - requirements.txt
      - vercel.json
      - .vercel/project.json
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  get the source
      - uses: actions/checkout@v4

      # 2️⃣  build the docs locally
      - name: Set up Python & build MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdocs build

      # 3️⃣  install Node + Vercel CLI
      - name: Set up Node 18 & install Vercel CLI
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g vercel@latest   # adds `vercel` to $PATH

      # 4️⃣  upload the already-built `site/` folder
      - name: Deploy to Vercel (prod)
        run: vercel deploy site --prod --yes --token ${{ secrets.VERCEL_TOKEN }}

      # 5️⃣  (optional) show the deployment URL in the log
      - name: Show last production deploy URL
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod ls | head -n 5
