name: Deploy Documentation

on:
  push:
    paths:
      - docs/**
      - mkdocs.yml
      - requirements.txt
      - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Docs
        run: mkdocs build

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel deploy --prod --yes site --token ${{ secrets.VERCEL_TOKEN }}
